setup action
brainly/autoupdate-branch pull request #1
Opened 2021-02-04 13:05 UTC by Fasosnql

2021-02-05 21:42 UTC, dsmileybrainly commented on src/index.ts
> +      while (detailedPr.data.mergeable === null) {
If I understand correctly why you `wait`, this might be better done with `setInterval`. IE:
```
const interval = setInterval(async () => {
   const resolved = detailedPr.data.mergeable ?? -1; // will return -1 only for undefined of null
  if (resolved < 0) return;
  // remove the interval
  clearInterval(interval);
  // do your thing
}, 100); // use a shorter timeout since we can poll
```

2021-02-05 21:42 UTC, dsmileybrainly commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
Collapse generated files in settings.

2021-02-08 11:54 UTC, Fasosnql commented on yarn.lock
> +# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
done

2021-02-08 13:11 UTC, Fasosnql commented on src/index.ts
> +      while (detailedPr.data.mergeable === null) {
agree, changed into interval

2021-02-08 19:46 UTC, dsmileybrainly approved these changes

2021-02-10 09:15 UTC, maciekbb requested changes

2021-02-10 09:15 UTC, maciekbb commented on src/index.ts
> +  for (const pr of prs) {
I'd rather avoid async operations in a for loop. I'm not sure we are properly waiting for all of them to complete.

How about doing something like
```
await Promise.all(prs.map(processPrAsync))
```

2021-02-10 09:15 UTC, maciekbb commented on src/index.ts
> +        if (detailedPr.data.mergeable === null) {
Could we extract this into a function? E.g.
```
await waitForMergableFlagToBeSet()
```

Also I'd await `setInterval` as it is fired in regular intervals (every 500ms). In case `await client.pulls.get` is slow this is a problem. Let's refactor it to `setTimeout` so you schedule next API call after the previous one is completed.

2021-02-10 09:15 UTC, maciekbb commented on README.md
> +A github action to auto update labeled branches with base branch.
I'd also emphasise that it can be a great companion to github automerge feature

2021-02-11 12:19 UTC, Fasosnql commented on README.md
> +A github action to auto update labeled branches with base branch.
done

2021-02-11 12:27 UTC, Fasosnql commented
Regarding whole logic I needed to re-think it. @maciekbb is right that `innterval` actually isn't the best option here because we need to wait till one rq will be completed to start another one, with interval we will start next rq anyway.

I created a diagram for it to visualise what I want to achieve and to point which part of code is responsible for particular part of diagram:
![image](https://user-images.githubusercontent.com/13320330/107636122-79c2a800-6c6c-11eb-8f88-fadea6c04c80.png)

So in case of `block 1` I decided to solve it with recursive calling `getPRDetails` and in each call add `500ms` delay. Here is the code responsible for `block 1`:
```
async function getPRDetails(pr, client) {
  await wait(500);
  const details = await client.pulls.get({
    ...context.repo,
    pull_number: pr.number,
  });

  if (details.data.mergeable !== null) {
    return details;
  } else {
    return getPRDetails(pr, client)
  }
}
```

and here is code responsible for `block 2` - in addition - in this action we are not sending slack notification but only returning proper output:
```
async function registerAction(pr, client) {
  const {data} = await getPRDetails(pr, client);

  if (data.mergeable) {
    await client.pulls.updateBranch({
      ...context.repo,
      pull_number: pr.number,
    });
  } else {
    core.setOutput('hasConflicts', true);
    core.setOutput('conflictedPullRequestJSON', JSON.stringify({
      title: data.title,
      url: data.html_url,
      user: {
        login: data.user.login,
        url: data.user.html_url,
        avatarUrl: data.user.avatarUrl
      }
    }));
  }
}
```

@dsmileybrainly @maciekbb @radekwarisch

2021-02-11 14:24 UTC, radekwarisch approved these changes

2021-02-12 09:25 UTC, maciekbb approved these changes

2021-02-12 09:25 UTC, merged